name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t nyxelis-api:latest .

      - name: Save Docker image
        run: docker save nyxelis-api:latest -o nyxelis-api.tar

      - name: Copy files to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "nyxelis-api.tar,docker-compose.yml,init-schema.sql"
          target: "/home/ec2-user/nyxelis/"

      - name: Deploy on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ec2-user/nyxelis
            docker load -i nyxelis-api.tar
            rm nyxelis-api.tar
            docker-compose down
            docker-compose up -d
            docker-compose logs --tail=50 nyxelis-api
