name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Prepare Docker context
        run: |
          mkdir -p /app
          cp target/starter-0.0.1-SNAPSHOT.jar /app/app.jar
          cp Dockerfile /app/Dockerfile
          cp docker-compose.yml /app/docker-compose.yml
          cp init-schema.sql /app/init-schema.sql

      - name: Build Docker image
        run: docker build -t nyxelis-api /app

      - name: Save Docker image
        run: docker save nyxelis-api:latest -o nyxelis-api.tar

      - name: Copy image to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "nyxelis-api.tar"
          target: "/home/ec2-user/"

      - name: Deploy on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker load -i /home/ec2-user/nyxelis-api.tar
            rm /home/ec2-user/nyxelis-api.tar
            docker-compose up -d
            docker-compose logs --tail=50 nyxelis-api
